---
title: "Data Visualization With ggplot2"
author: "Rafael Henriques"
date: "9/7/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
# Do cars with big engines use more fuel than cars with small engines?
```

```{r}
# mpg data frame is a rectangular collection (fields and records)
# found in (ggplot2::mpg)
# displ -  car’s engine size, in liters
# hwy - a car’s fuel efficiency on the highway
mpg
```

```{r}
# Help
help(mpg)
```

```{r}
# Creating a ggplot2
## Function geom_point() adds a layer of points to your plot,
## which creates a scatterplot
ggplot(data=mpg) + geom_point(mapping=aes(x=displ,y=hwy))
```

```{r}
# Graphic Template
# ggplot(data=<DATA>) + <GEOM_FUNCTION>(mapping=aes(<MAPPINGS>))

ggplot(data = mpg)
```

```{r}
# Import mtcars dataset
mtcars <- dput(mtcars)
nrow(mtcars)
ncol(mtcars)
ggplot(data=mpg) + geom_point(mapping=aes(x=cyl,y=hwy))
```

```{r}
# Why is it not an useful graph?
ggplot(data=mpg) + geom_point(mapping=aes(x=class,y=drv))
```

```{r}
# Color advised for discrete variables
p = ggplot(data = mpg)
p + geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
# Warning: Using size for a discrete variable is not advised.
# Size is advised for continuous variables
ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

```{r}
# Top
    ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
# Bottom
    ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

```{r}
# Make all plotted points blue
# stroke aesthetic
ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy), color = "blue", stroke=5)
```

```{r}
# Facets: subplots that each display one subset of the data
ggplot(data=mpg) +
      geom_point(mapping = aes(x=displ, y=hwy)) +
      facet_wrap(~class, nrow=2)
```

```{r}
# Facet the plot on the combination of two variables
# Generally those variables are discrete (drv and cyl in this case)
ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy)) +
      facet_grid(drv ~ cyl)
```

```{r}
ggplot(data = mpg) +
          geom_point(mapping = aes(x = displ, y = hwy)) +
          facet_grid(drv ~ .)
```

```{r}
ggplot(data = mpg) +
          geom_point(mapping = aes(x = displ, y = hwy)) +
          facet_grid(. ~ cyl)
```

```{r}
ggplot(data = mpg) +
          geom_point(mapping = aes(x = displ, y = hwy)) +
          facet_wrap(~ class, nrow = 2)
```

# Geometric Objects

```{r}
# For example, bar charts use bar geoms, line charts use line geoms, boxplots use boxplot geoms, and so on. Scatterplots break the trend; they use the point geom.

# left
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
# right
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
 
```

```{r}
# Different linetype, for each unique value of the variable
ggplot(data = mpg) +
      geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```

```{r}
# ggplot2 provides over 30 geoms
ggplot(data=mpg) +
    geom_smooth(mapping=aes(x=displ, y=hwy))

ggplot(data=mpg) +
  geom_smooth(mapping=aes(x = displ, y=hwy, group=drv))

ggplot(data=mpg) +
  geom_smooth(mapping=aes(x=displ, y=hwy, color=drv), show.legend=TRUE)
```

```{r}
# Display multiple geoms in the same plot
ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy)) +
      geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r}
# Imagine if you wanted to change the y-axis to display cty instead of hwy. You’d need to change the variable in two places, and you might forget to update one. You can avoid this type of repetition by passing a set of mappings to ggplot().

# Global mapping, by mapping in ggplot(...) method

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() + 
  geom_smooth()
```

```{r}
# Local mappings to extend or overwrite the global mappings for that layer only.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
      geom_point(mapping = aes(color = class)) +
      geom_smooth()
```

```{r}
# Smooth line displays just a subset of the mpg dataset
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
      geom_point(mapping = aes(color = class)) +
      geom_smooth(
        data = filter(mpg, class == "subcompact"), se = FALSE )
```

```{r}
# Plot exactly the same
 ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
         geom_point() +
         geom_smooth()
       ggplot() +
         geom_point(
data = mpg,
mapping = aes(x = displ, y = hwy) )+
         geom_smooth(
           data = mpg,
           mapping = aes(x = displ, y = hwy)
)
```

# Statistical Transformations
stat: statistical transformation

```{r}
# Diamonds dataset comes in ggplot2 and contains information about ~54,000 diamonds, including the price, carat, color, clarity, and cut of each diamond
# Bar charts seem simple, but they are interesting because they reveal something subtle about plots.
ggplot(data = diamonds) +
      geom_bar(mapping = aes(x = cut))

#you can re-create the previous plot using stat_count() instead of geom_bar():
ggplot(data = diamonds) +
      stat_count(mapping = aes(x = cut))
```

```{r}
# Deep a bit in how bar charts are built
demo <- tribble(
          ~a,      ~b,
          "bar_1", 20,
          "bar_2", 30,
          "bar_3", 40
)
ggplot(data = demo) +
  geom_bar(
    mapping = aes(x = a, y = b), stat = "identity"
  )
```

```{r}
# Proportion bar chart
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```

```{r}
# Summarizes the y values for each unique x value
ggplot(data = diamonds) +
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

```{r}
# WITHOUT GROUP
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop..))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..))

# WITH GROUP
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop.., group = 1))
```

# Position Adjustments

```{r}
ggplot(data = diamonds ) +
  geom_bar(mapping = aes(x = cut, color = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
```

```{r}
# Map the fill aesthetic to another vari‐ able, like clarity: the bars are automatically stacked.
ggplot(data = diamonds) +
      geom_bar(mapping = aes(x = cut, fill = clarity))
```

```{r}
# position = "identity" will place each object exactly where it falls in the context of the graph. It's more useful for 2D geoms, like points, where it is the default.
ggplot(
  data = diamonds,
  mapping = aes(x = cut, fill = clarity)
) +
geom_bar(alpha = 1/5, position = "identity")
ggplot(
  data = diamonds,
  mapping = aes(x = cut, color = clarity)
  ) +
geom_bar(fill = NA, position = "identity")
```

```{r}
# position = "fill"; Useful to compare proportions
ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = clarity),
    position = "fill"
  )
```

```{r}
# position = "dodge"; It Makes it easier to compare individual values
ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = clarity),
    position = "dodge"
  )
```

```{r}
# position = "jitter"; It adds a small amount of random noise to each point. Let us see where there is more density.
ggplot(data = mpg) +
  geom_point(
    mapping = aes(x = displ, y = hwy),
    position = "jitter"
  )
```

```{r}
# geom_jitter() - it adds a small amount of random variation to the location of each point
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + geom_jitter()
```


```{r}
# geom_count() - it counts the number of observations at each location; useful for discrete data and overplotting
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + geom_count()
```

# Coordinate System

```{r}
# Vertical box plot
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot()

# Horizontal box plot through axis flipping
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
# Print a map through coordinates
nz <- map_data("nz")
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black")
```

```{r}
# coord_quickmap() - sets the aspect ratio correctly for maps
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap()
```

```{r}
# labs - Modify axis, legend, and plot labels
bar <- ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = cut), show.legend = FALSE,
    width = 1
    ) +
  theme(aspect.ratio = 1) + 
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()
```

```{r}
# coord_fixed() - forces a specific ratio between the physical representation of data units on the axes
# geom_abline() - Add a reference line specified by the slope and intercept
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() +
  geom_abline() +
  coord_fixed()
```

# The Layered Grammar of Graphics

```{r}
# Function Template

# ggplot(data = <DATA>) +
#       <GEOM_FUNCTION>(
#          mapping = aes(<MAPPINGS>),
#          stat = <STAT>,
#          position = <POSITION>
# )+ <COORDINATE_FUNCTION> + <FACET_FUNCTION>
```

```{r}

```


```{r}
# Read the documentation using the ?<expression>
?mpg
```

```{r}
# List the variables
names(mpg)
```
```{r}
# List the dimensions
dim(mpg)
```


```{r}
# Class of the object
class(mpg)
```

```{r}
# print first 2 rows of the dataframe
head(mpg,2)
```
```{r}
# print last 2 rows of the dataframe
tail(mpg,2)
```
```{r}
summary(mpg)
```

```{r}
library(skimr)
skim(mpg)
```

